import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const Space = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pricing",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Space.className}>
        {children}
      </body>
    </html>
  );
}
